In [ ]:
import numpy as np

In [ ]:
class Perceptron:
  def __init__(self,input_size, learning_rate=0.001,epooch=1000):
    self.weight=np.zeros(input_size+1)
    self.learning_rate=learning_rate
    self.epooch=epooch

  def activation(self,x):
    return 1 if x>0  else 0

  def predict(self,x):
    z=self.weight.T.dot(x)
    return self.activation(z)

  def training(self,training_input,labels):
    for _ in range(self.epooch):
      for x,y in zip(training_input,labels):
        x=np.insert(x,0,1)
        prediction=self.predict(x)
        self.weight +=self.learning_rate*(y-prediction) *x

  def accuracy(self,test_input,test_labels):
    correctness=0
    for x,y in zip(test_input,test_labels):
      x = np.insert(x, 0, 1)
      y_predict=self.predict(x)
      if y_predict==y:
        correctness+=1

    return correctness/len(test_input)



In [ ]:
training_input=np.array([[0,0],[0,1],[1,0],[1,1]])
lables=np.array([0,0,0,1])

perceptron= Perceptron(input_size=2)
perceptron.training(training_input,lables)


In [ ]:
perceptron.weight

array([-0.002,  0.002,  0.001])

In [ ]:
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_labels = np.array([0, 0, 0, 1])

for test_input in test_inputs:
    test_input_with_bias = np.insert(test_input, 0, 1)  # Adding bias term
    print(f"Input: {test_input}, Predicted Output: {perceptron.predict(test_input_with_bias)}")

# Calculate and print the accuracy
accuracy = perceptron.accuracy(test_inputs, test_labels)
print(f"Accuracy: {accuracy * 100:.2f}%")

Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 1
Accuracy: 100.00%


In [ ]:
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for test_input in test_inputs:
    test_input_with_bias = np.insert(test_input, 0, 1)  # Adding bias term
    print(f"Input: {test_input}, Predicted Output: {perceptron.predict(test_input_with_bias)}")

Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 1


# There is limitation in perceptrons - like it doesn't work with XOR case.

In [ ]:
training_input=np.array([[0,0],[0,1],[1,0],[1,1]])
lables=np.array([0,1,1,0])

perceptron2= Perceptron(input_size=2)
perceptron2.training(training_input,lables)

In [ ]:
perceptron2.weight

array([ 0.001, -0.001,  0.   ])

In [ ]:
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for test_input in test_inputs:
    test_input_with_bias = np.insert(test_input, 0, 1)  # Adding bias term
    print(f"Input: {test_input}, Predicted Output: {perceptron.predict(test_input_with_bias)}")

Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 1


# In raw Python

In [4]:
import numpy as np

class Perceptron:
  def __init__(self,input_size, learning_rate=0.001,epooch=1000):
    self.weight=np.zeros(input_size+1)
    self.learning_rate=learning_rate
    self.epooch=epooch

  def activation(self,x):
    return 1 if x>0  else 0

  def predict(self,x):
    z=self.weight.T.dot(x)
    return self.activation(z)

  def training(self,training_input,labels):
    for _ in range(self.epooch):
      for x,y in zip(training_input,labels):
        x=np.insert(x,0,1)
        prediction=self.predict(x)
        self.weight +=self.learning_rate*(y-prediction) *x

  def accuracy(self,test_input,test_labels):
    correctness=0
    for x,y in zip(test_input,test_labels):
      x = np.insert(x, 0, 1)
      y_predict=self.predict(x)
      if y_predict==y:
        correctness+=1

    return correctness/len(test_input)

training_input=np.array([[0,0],[0,1],[1,0],[1,1]])
lables=np.array([0,0,0,1])

perceptron= Perceptron(input_size=2)
perceptron.training(training_input,lables)

test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_labels = np.array([0, 0, 0, 1])

for test_input in test_inputs:
    test_input_with_bias = np.insert(test_input, 0, 1)  # Adding bias term
    print(f"Input: {test_input}, Predicted Output: {perceptron.predict(test_input_with_bias)}")

# Calculate and print the accuracy
accuracy = perceptron.accuracy(test_inputs, test_labels)
print(f"Accuracy: {accuracy * 100:.2f}%")




Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 1
Accuracy: 100.00%


## In tensorflow -


In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


# Sample data
X = tf.constant([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]], dtype=tf.float32)
y = tf.constant([[0.0], [1.0], [1.0], [1.0]], dtype=tf.float32)

# Define the Perceptron model
model=Sequential([Dense(1,input_dim=2,activation='sigmoid')])

#compile model
model.compile(optimizer='sgd',loss='binary_crossentropy')

epochs=1000

history=model.fit(X,y,epochs=epochs,verbose=0)

# Print the final loss
final_loss = history.history['loss'][-1]
print(f'Final Loss: {final_loss:.4f}')

# Testing the model
predictions = model.predict(X).round()
print(f'Predictions:\n{predictions}')

Final Loss: 0.2678
1/1 [==============================] - 0s 164ms/step
Predictions:
[[0.]
 [1.]
 [1.]
 [1.]]


# In pytorch

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim


class Perceptron(nn.Module):
  def __init__(self,input_dim):
    super(Perceptron,self).__init__()
    self.fc= nn.Linear(input_dim,1)

  def forward(self,x):
    x=self.fc(x)
    return torch.sigmoid(x)


# Sample data
X = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]], dtype=torch.float32)
y = torch.tensor([[0.0], [1.0], [1.0], [1.0]], dtype=torch.float32)


input_dim= X.shape[1]
model=Perceptron(input_dim)
criterion=nn.BCELoss()
optimizer=optim.SGD(model.parameters(),lr=0.001)


epochs= 10000

for epoch in range(epochs):
  model.train()
  optimizer.zero_grad()
  outputs=model(X)
  loss= criterion(outputs,y)
  loss.backward()
  optimizer.step()

  if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

model.eval()


with torch.no_grad():
  test_output=model(X)
  predictions=test_output.round()
  print(f'Predictions:\n{predictions}')


Epoch [100/10000], Loss: 0.9427
Epoch [200/10000], Loss: 0.9112
Epoch [300/10000], Loss: 0.8818
Epoch [400/10000], Loss: 0.8544
Epoch [500/10000], Loss: 0.8289
Epoch [600/10000], Loss: 0.8052
Epoch [700/10000], Loss: 0.7831
Epoch [800/10000], Loss: 0.7625
Epoch [900/10000], Loss: 0.7435
Epoch [1000/10000], Loss: 0.7257
Epoch [1100/10000], Loss: 0.7092
Epoch [1200/10000], Loss: 0.6938
Epoch [1300/10000], Loss: 0.6795
Epoch [1400/10000], Loss: 0.6661
Epoch [1500/10000], Loss: 0.6537
Epoch [1600/10000], Loss: 0.6421
Epoch [1700/10000], Loss: 0.6312
Epoch [1800/10000], Loss: 0.6210
Epoch [1900/10000], Loss: 0.6115
Epoch [2000/10000], Loss: 0.6026
Epoch [2100/10000], Loss: 0.5942
Epoch [2200/10000], Loss: 0.5863
Epoch [2300/10000], Loss: 0.5789
Epoch [2400/10000], Loss: 0.5719
Epoch [2500/10000], Loss: 0.5652
Epoch [2600/10000], Loss: 0.5590
Epoch [2700/10000], Loss: 0.5531
Epoch [2800/10000], Loss: 0.5474
Epoch [2900/10000], Loss: 0.5421
Epoch [3000/10000], Loss: 0.5370
Epoch [3100/10000],